name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [main]

jobs:
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.ref != 'refs/heads/main' }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'stable'
        install-chromedriver: true

    - name: Install Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest' 
          
    - name: Run tests
      run: mvn clean verify -P testng-tests

    - name: List current directory contents
      run: |
        ls -larth ./
        ls -larth target/
        find target/ -name 'TEST-*.xml'|awk -F":" '{print $1}'
        find target/ -name 'TEST-*.xml'|xargs grep testsuite|grep testng|grep tests=|awk -F":" '{print $1,$2}'|awk -F" " '{print $1,$5}'
        find target/ -name 'TEST-*.xml'|xargs grep testsuite|grep surefire|grep tests=|awk -F":" '{print $1,$6}'|awk -F" " '{print $1, $6}'

    - name: Load Allure test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build allure test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: target/allure-results

    - name: Upload testng report
      uses: actions/upload-artifact@v4
      with:
        name: maven-testng-report
        path: |
          target/surefire-reports/
          
    - name: Upload allure report
      uses: actions/upload-artifact@v4
      with:
        name: maven-allure-report
        path: |
          allure-history

    - name: Stage only current surefire reports
      run: |
        rm -rf badges-input
        mkdir -p badges-input
        cp -r target/surefire-reports/junitreports badges-input/
        [[ -d target/failsafe-reports ]] && cp -r target/failsafe-reports/junitreports badges-input/
        find target/ -name '*.xml'|xargs rm
        find gh-pages/ -name '*.xml'|xargs rm

    - name: Generate Test badge
      if: success() || failure()
      uses: gaelgirodon/ci-badges-action@v1
      with:
        gist-id: ${{ secrets.GIST_ID }} 
        token: ${{ secrets.GIST_TOKEN }}

  publish-reports:
    name: Upload and Publish Reports to GitHub Pages
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Compile for Sonar
      run: mvn compile

    - name: Download testng reports
      uses: actions/download-artifact@v4
      with:
        name: maven-testng-report
        path: |
          reports/testng-reports

    - name: Download allure reports
      uses: actions/download-artifact@v4
      with:
        name: maven-allure-report
        path: |
          reports/allure-history

    - name: List current directory contents
      run: |
        ls -larth ./
        ls -larth reports/

    - name: Combine Allure TestNG reports
      if: success() || failure()
      run: |
        mkdir -p target/combined
        mkdir -p target/combined/testng
        cp -r reports/allure-history/* target/combined/
        cp -r reports/testng-reports/* target/combined/testng

    - name: Deploy reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/combined
        force_orphan: true
